### PR TITLE
feat: add inactive class to get more control on appearance

### PR DESCRIPTION
**Pull request by mcanouil**
This PR does:

- Add `agenda-inactive` CSS class.
- Tweak the default CSS to have something more "pretty".

### CODE REVIEW

**Comment by andrie** [comment]
Thanks for these suggestions.

I think you can simplify this and achieve your desired outcome without modifying the Lua script.  What I mean is that you can already target the `.agenda` class and the `.agenda-active` class separately.

The changes you propose should be easy to implement by the end-user, without trying to second-guess what aesthetics they prefer.  (An example of doing this would be great, though!)

So, at this stage, I think a discussion about how much pre-canned CSS we want to provide for different use cases is possibly more fruitful.

For example, I'm absolutely sure that the current border around the agenda can, no doubt, be improved.  And although I like your suggestion of having transparent inactive text, this may well have implications for accessibility (it reduces contrast that may be important for partially sighted people).

I'd be open to suggestions for different options, though.  For example, having an option that explicitly adds a `.agenda-active-box` class.

If you agree, then perhaps we create a new issue for design decisions and have the discussion there?

**Comment by mcanouil** [comment]
The opacity cannot be set in `agenda` alone and revert in `agenda-active`, thus the idea to have the two classes to allow more control over the items, no matter what CSS parameters the end-user wants.

> And although I like your suggestion of having transparent inactive text, this may well have implications for accessibility (it reduces contrast that may be important for partially sighted people).

Indeed, with the current font colour and background colour, opacity should be no lower than 0.6 depending on font-size and font-weight attributes.
LaTex-style progress TOC is not really an a11y friend.

For short,
- the opacity thing can be reverted and set by the user I agree. (I tweaked the box CSS and added font-weight 4eb86d8224979905a9cd6fb1790920b28eee79bb)
- I would keep the two classes (_i.e._, "active"/"inactive") because `agenda` is set to a `<div>` not `<ul>` and `agenda-active` is also set to `<div>` not `<li>`, thus leading to cumbersome CSS escalation making harder for user to get proper control even with custom CSS.


PS: there a jQuery approach to this for Reveal JS, I did look yet into detail <https://github.com/e-gor/Reveal.js-TOC-Progress>

**Comment by andrie** [comment]
I've just spent an hour to convince myself that you're indeed correct: I thought I could use CSS qualifiers to isolate non-active items, but I was unable to.  Your approach is good.

So, let me bounce one more idea, and that is to have classes for:

* `.inactive .pre-active `
* `.active`
* `.inactive .post-active `

In other words, add classes that allow you to have different behaviour for history, active and future.

What do you think?

**Comment by mcanouil** [comment]
> I've just spent an hour to convince myself that you're indeed correct: I thought I could use CSS qualifiers to isolate non-active items, but I was unable to. Your approach is good.

I went there 😅 "glad" we arrived to the same place 😉

> So, let me bounce one more idea, and that is to have classes for:
> 
> * `.inactive .pre-active `
> * `.active`
> * `.inactive .post-active `
> 
> In other words, add classes that allow you to have different behaviour for history, active and future.

I did not think that far, but I think it makes a lot of sense to allow to distinguish past sections from the future ones.

**Comment by mcanouil** [comment]
Style simply for the sake of the illustration (elements are commented in the css file).
image

**Comment by andrie** [comment]
Thanks for this contribution.  I've given up on getting a nice border around the items, so the current state of the repo is very similar to your original suggestion.

I've updated the css classes to all have `agenda-` prefixes, FYI.

Many thanks, again.

**Pull request merged**
